# Generated by Django 4.2 on 2023-05-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
