# Generated by Django 4.2 on 2023-05-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='member_ship',
            new_name='membership',
        ),
    ]
