# Generated by Django 4.2 on 2023-05-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_email_address_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
