# Generated by Django 4.2 on 2023-05-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancle_order', 'can cancle order')]},
        ),
    ]
